pub mod membrane;
pub mod neuron;
pub use membrane::{
    APICAL_LEAK_SHIFT, BAC_APICAL_THRESHOLD, BAC_PLATEAU_TICKS, BASAL_LEAK_SHIFT,
    BURST_REFRACTORY_TICKS, COUPLING_SHIFT, FLAG_BURST_MODE, FLAG_INHIBITORY,
    PLATEAU_COUPLING_SHIFT, REFRACTORY_TICKS, SOMA_LEAK_SHIFT, THRESHOLD_BASE,
    THRESHOLD_DECAY_SHIFT, THRESHOLD_STEP, V_RESET,
};
pub use neuron::{
    DendriticSuperNeuron, GateState, MAILBOX_EMPTY, MAILBOX_NIL, MailboxDrain, MailboxNode,
    SynapseBlock, synaptic_efficacy_q16,
};
